version: "3.3"  # optional since v1.27.0
services:
  ca_root:
    container_name: ca_root
    ports:
      - "8000:80"
    image: cav1:latest
    restart: unless-stopped
    environment:
      - CA_NAME=root
      - CA_TYPE=root
      - CA_CUR_ENV=server
      - CA_TOP_NAME=nil
  ca1:
    container_name: ca1
    ports:
      - "8001:80"
    image: cav1:latest
    restart: unless-stopped
    environment:
      - CA_NAME=ca1
      - CA_TYPE=intermediate
      - CA_CUR_ENV=server
      - CA_TOP_NAME=ca_root
  ca2:
    container_name: ca2
    ports:
      - "8002:80"
    image: cav1:latest
    restart: unless-stopped
    environment:
      - CA_NAME=ca2
      - CA_TYPE=intermediate
      - CA_CUR_ENV=server
      - CA_TOP_NAME=ca_root
  ca1_1:
    container_name: ca1_1
    ports:
      - "8003:80"
    image: cav1:latest
    restart: unless-stopped
    environment:
      - CA_NAME=ca1_1
      - CA_TYPE=intermediate
      - CA_CUR_ENV=server
      - CA_TOP_NAME=ca1
  ca2_2:
    container_name: ca2_2
    ports:
      - "8004:80"
    image: cav1:latest
    restart: unless-stopped
    environment:
      - CA_NAME=ca2_2
      - CA_TYPE=intermediate
      - CA_CUR_ENV=server
      - CA_TOP_NAME=ca2
networks:
    default:
       external:
         name: ca_network
